services:

  miner_server:
    build:
      context: ..
      dockerfile: ./.docker/miner/Dockerfile
    image: miner_server
    container_name: miner_server
    environment:
      SERVER_PORT: 5000
      MAX_TRIES: 3
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    command: python model_servers/miner.py
    restart: unless-stopped
    networks:
      - solidity-audit

  miner:
    build:
      context: ..
      dockerfile: ./.docker/neuron/Dockerfile
    image: miner
    container_name: miner
    environment:
      MNEMONIC_HOTKEY: ${MINER_HOTKEY_MNEMONIC}
      NETWORK_UID: "92"
      CHAIN_ENDPOINT: "wss://entrypoint-finney.opentensor.ai:443/"
      EXTERNAL_IP: "198.135.49.49"
      MODEL_SERVER: 'http://miner_server:5000'
      BT_AXON_PORT: 8091
    command: python neurons/miner.py
    ports:
      - 8091:8091
    restart: unless-stopped
    networks:
      - solidity-audit


networks:
  solidity-audit: